[workspace]

members = [ "rust/collection", 
    "rust/date_types", "rust/enums", "rust/error",
    "rust/guessing_game", "rust/lifttimes", "rust/modules",
    "rust/ownership", "rust/restaurant", "rust/structure", "rust/traits",
]
